"""Generate a TradingView Pine Script v5 strategy that mirrors the app's
per-stock TECHNICAL backtest (app/signals/technical.py + engine thresholds/stops).

Purpose: paste into TradingView on a `JSE:TICKER` chart to cross-check our
backtest. It reproduces the same sub-signals, weights, thresholds, ATR stop and
horizon exit, and applies costs — so results should broadly agree in direction.
It is NOT identical: TradingView uses its own JSE data feed, STT (buy-only)
can't be modelled separately from TradingView's symmetric commission, and fills
differ. Read it as a second opinion, not a to-the-decimal match.

Only the technical layer is reproduced (macro / sentiment / cross-sectional
momentum are not single-symbol constructs).
"""

from __future__ import annotations

from app.config import Settings
from app.signals import technical as tech


def build_pine(settings: Settings) -> str:
    # Approximate per-side cost as brokerage + slippage (percent). STT is
    # buy-only and can't be expressed in TradingView's symmetric commission, so
    # it is folded in with a note rather than silently ignored.
    per_side = float(settings.brokerage_pct + settings.slippage_pct)

    return f"""//@version=5
// ============================================================================
//  Crypto Technical Strategy — generated by your Crypto Swing-Trader app
//  Mirrors the app's TECHNICAL backtest so you can compare in TradingView.
//  Use on a crypto symbol, e.g. BINANCE:BTCUSDT, BINANCE:ETHUSDT.
//
//  NOT a to-the-decimal match with the app: different fills; commission below
//  approximates exchange fee + slippage (per side).
// ============================================================================
strategy("Crypto Technical (app)", overlay=true, initial_capital=10000,
     default_qty_type=strategy.percent_of_equity, default_qty_value=100,
     process_orders_on_close=true,
     commission_type=strategy.commission.percent, commission_value={per_side:.4f},
     pyramiding=0)

// --- Tunable inputs (defaults = your app's effective settings) ---
buyThresh  = input.float({settings.buy_threshold}, "Buy threshold (fused score)")
sellThresh = input.float({settings.sell_threshold}, "Sell threshold")
atrMult    = input.float({float(settings.atr_stop_multiple)}, "ATR stop multiple")
horizon    = input.int({settings.default_horizon_days}, "Horizon (bars) exit")

// --- Indicators (same windows as the app) ---
sma20 = ta.sma(close, 20)
sma50 = ta.sma(close, 50)
rsiV  = ta.rsi(close, 14)
[macdLine, sigLine, hist] = ta.macd(close, 12, 26, 9)
atrV  = ta.atr(14)
eps   = {tech._EPS}

// --- Technical score (weights match app/signals/technical.py) ---
var float score = 0.0
score := 0.0
// 1) SMA20 vs SMA50 trend (near-equal = neutral)
score := score + (sma20 > sma50 * (1 + eps) ? {tech._W_TREND_CROSS} : sma20 < sma50 * (1 - eps) ? {-tech._W_TREND_CROSS} : 0.0)
// 2) Price vs SMA50
score := score + (close > sma50 * (1 + eps) ? {tech._W_PRICE_VS_SMA} : close < sma50 * (1 - eps) ? {-tech._W_PRICE_VS_SMA} : 0.0)
// 3) RSI (mean-reversion bias)
score := score + (rsiV < 30 ? {tech._W_RSI} : rsiV > 70 ? {-tech._W_RSI} : 0.0)
// 4) MACD histogram sign
score := score + (hist > eps ? {tech._W_MACD} : hist < -eps ? {-tech._W_MACD} : 0.0)
// 5) Breakout: close >= prior {tech._BREAKOUT_LOOKBACK}-day high on > {tech._BREAKOUT_VOL_MULT}x avg volume
priorHigh = ta.highest(high, {tech._BREAKOUT_LOOKBACK})[1]
avgVol    = ta.sma(volume, {tech._BREAKOUT_LOOKBACK})[1]
breakout  = not na(priorHigh) and not na(avgVol) and avgVol > 0 and close >= priorHigh and volume > {tech._BREAKOUT_VOL_MULT} * avgVol
score := score + (breakout ? {tech._W_BREAKOUT} : 0.0)
// clamp to [-1, 1]
score := math.max(-1.0, math.min(1.0, score))

// --- Long-only entries/exits (matches the app: BUY signals only) ---
enoughHistory = bar_index > 50
var int entryBar = na
if enoughHistory and strategy.position_size == 0 and score >= buyThresh
    strategy.entry("Long", strategy.long)
    entryBar := bar_index

// ATR stop from the entry bar's close, and a horizon (bars-held) exit.
if strategy.position_size > 0
    stopPrice = strategy.position_avg_price - atrMult * atrV
    strategy.exit("Stop", from_entry="Long", stop=stopPrice)
    if not na(entryBar) and (bar_index - entryBar) >= horizon
        strategy.close("Long", comment="Horizon")

// --- Plots ---
plot(sma20, "SMA20", color=color.new(color.blue, 0))
plot(sma50, "SMA50", color=color.new(color.orange, 0))
plot(score, "Score", display=display.data_window)
"""
