#!/usr/bin/env bash
#
# Provision the Crypto Swing-Trader ALONGSIDE an existing VirtualSchool install
# on the same Ubuntu server. It reuses the nginx, MySQL, certbot and firewall
# that VirtualSchool's provision.sh already set up — it does NOT reinstall or
# reconfigure them, and it never touches the virtual_school database or site.
#
# Run as root on the server:
#     bash /srv/cryptotrader/deploy/provision-crypto.sh trade.mad-apps.co.za you@example.com
#
# Idempotent — safe to run twice. It stops with a placeholder .env; fill in the
# login secret, then run deploy-crypto.sh.

set -euo pipefail

DOMAIN="${1:-trade.mad-apps.co.za}"
CERTBOT_EMAIL="${2:-}"

APP_USER="cryptotrader"
APP_DIR="/srv/cryptotrader"
DB_NAME="crypto_trader"
DB_USER="crypto_user"

say()  { printf '\n\033[1;36m==> %s\033[0m\n' "$1"; }
warn() { printf '\033[1;33m !! %s\033[0m\n' "$1"; }
fail() { printf '\n\033[1;31m!! %s\033[0m\n' "$1" >&2; exit 1; }

[[ $EUID -eq 0 ]] || fail "Run this as root."

# --- sanity: the shared infrastructure should already be here from the school --
command -v nginx   >/dev/null 2>&1 || fail "nginx not found. Provision VirtualSchool first (it installs the shared nginx/MySQL/certbot)."
command -v mysql   >/dev/null 2>&1 || fail "mysql client not found — is MySQL installed?"
command -v certbot >/dev/null 2>&1 || warn "certbot not found; TLS step will be skipped. Install with: apt-get install -y certbot"

# Node is needed to build the frontend; the school installs Node 20.
if ! command -v node >/dev/null 2>&1 || [[ "$(node -v | cut -c2- | cut -d. -f1)" -lt 18 ]]; then
  say "Installing Node.js 20 (needed by Vite)"
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y -qq nodejs
fi

# python venv tooling (the school installed python3-venv already, but be safe)
apt-get install -y -qq python3-venv python3-dev build-essential pkg-config >/dev/null 2>&1 || \
  warn "could not apt-get python build deps — continuing (they may already be present)"

# ------------------------------------------------------------------- user ----
say "Creating the service user"
if ! id "$APP_USER" >/dev/null 2>&1; then
  adduser --system --group --home "$APP_DIR" --shell /usr/sbin/nologin "$APP_USER"
  echo "  created $APP_USER"
else
  echo "  $APP_USER already exists"
fi
mkdir -p "$APP_DIR" "$APP_DIR/.cache/matplotlib"
chown -R "$APP_USER:$APP_USER" "$APP_DIR"
chmod 755 "$APP_DIR"   # nginx (www-data) must traverse into frontend/dist

# --------------------------------------------------------------- database ----
# A SECOND database + user on the SAME MySQL server. The school's virtual_school
# database and its user are not touched.
say "Creating the crypto_trader database on the existing MySQL"
systemctl is-active --quiet mysql || systemctl start mysql

DB_PASSWORD_FILE="/root/.cryptotrader-db-password"
if [[ -f "$DB_PASSWORD_FILE" ]]; then
  DB_PASSWORD="$(cat "$DB_PASSWORD_FILE")"
  echo "  reusing the existing database password"
else
  DB_PASSWORD="$(openssl rand -base64 30 | tr -d '/+=' | head -c 32)"
  printf '%s' "$DB_PASSWORD" > "$DB_PASSWORD_FILE"
  chmod 600 "$DB_PASSWORD_FILE"
  echo "  generated a database password (stored in $DB_PASSWORD_FILE)"
fi

mysql <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASSWORD}';
ALTER USER '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES
  ON \`${DB_NAME}\`.* TO '${DB_USER}'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL
echo "  database and user ready (isolated from virtual_school)"

# ------------------------------------------------------------------- .env ----
# pydantic-settings reads .env from the service WorkingDirectory (backend/).
say "Preparing backend/.env"
ENV_PATH="$APP_DIR/backend/.env"
mkdir -p "$APP_DIR/backend"
if [[ -f "$ENV_PATH" ]]; then
  echo "  $ENV_PATH already exists, leaving it alone"
else
  AUTH_SECRET_KEY="$(openssl rand -base64 48 | tr -d '\n')"
  cat > "$ENV_PATH" <<ENVFILE
# Generated by provision-crypto.sh on $(date -Is)

DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@127.0.0.1:3306/${DB_NAME}
APP_ENV=production
LOG_LEVEL=INFO
FRONTEND_ORIGIN=https://${DOMAIN}

# ---- Login gate (STRONGLY recommended before exposing to the internet) ----
# Leave blank to enrol a fresh QR:   .venv/bin/python -m app.auth_setup
# OR paste the base32 secret you already scanned into Google Authenticator so
# the same 6-digit codes work here too.
TOTP_SECRET=
AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
SESSION_TTL_HOURS=12
TOTP_ISSUER=Crypto Swing-Trader
TOTP_ACCOUNT=owner

# ---- Crypto market data (Binance public API — no key needed) ----
PRICE_PROVIDER=binance
BINANCE_BASE_URL=https://data-api.binance.vision
# Binance USDⓈ-M futures host for positioning data (funding/OI/etc). Change only
# if it's geo-blocked from the server (the app degrades gracefully if so).
BINANCE_FUTURES_BASE_URL=https://fapi.binance.com
QUOTE_CURRENCY=USDT
FEAR_GREED_URL=https://api.alternative.me/fng/
SENS_RSS_URL=https://cointelegraph.com/rss

# ---- Optional FREE keys — unlock extra context layers (safe to leave blank) ----
# FRED: macro regime (DXY/gold/US10y/S&P). https://fred.stlouisfed.org/docs/api/api_key.html
FRED_API_KEY=
# SoSoValue: spot BTC/ETH ETF net flows. https://sosovalue.com/developer
SOSOVALUE_API_KEY=

# ---- Other optional keys (safe to leave blank) ----
MARKETAUX_API_KEY=
EODHD_API_KEY=
ALPHAVANTAGE_API_KEY=
OILPRICE_API_KEY=
ENVFILE
  echo "  wrote $ENV_PATH with a generated AUTH_SECRET_KEY and DB password"
fi
chown "$APP_USER:$APP_USER" "$ENV_PATH"
chmod 600 "$ENV_PATH"

# ------------------------------------------------------------------ nginx ----
say "Installing the nginx bootstrap site (HTTP, for the ACME challenge)"
SITE_TLS=/etc/nginx/sites-available/cryptotrader
SITE_BOOT=/etc/nginx/sites-available/cryptotrader-bootstrap

[[ -f "$APP_DIR/deploy/nginx-cryptotrader.conf" ]] || warn "deploy/nginx-cryptotrader.conf missing — copy the code to $APP_DIR"

cp "$APP_DIR/deploy/nginx-cryptotrader-bootstrap.conf" "$SITE_BOOT"
cp "$APP_DIR/deploy/nginx-cryptotrader.conf" "$SITE_TLS"

# Security-headers snippet the TLS site includes in every location block.
mkdir -p /etc/nginx/snippets
cp "$APP_DIR/deploy/nginx-cryptotrader-security.conf" /etc/nginx/snippets/cryptotrader-security.conf

# Shared webroot (created by the school). Make sure it exists regardless.
mkdir -p /var/www/certbot/.well-known/acme-challenge
[[ -f /var/www/certbot/holding.html ]] || cat > /var/www/certbot/holding.html <<'HOLD'
<!doctype html><meta charset="utf-8"><title>Not ready yet</title>
<body style="font-family:system-ui;padding:3rem;max-width:40rem">
<h1>Not ready yet</h1><p>This app is being set up. It will be available over HTTPS shortly.</p>
HOLD
chown -R www-data:www-data /var/www/certbot

ln -sf "$SITE_BOOT" /etc/nginx/sites-enabled/cryptotrader-bootstrap
if nginx -t 2>/dev/null; then
  systemctl reload nginx
  echo "  reloaded nginx with the crypto bootstrap site (school site untouched)"
else
  nginx -t
  warn "nginx config test failed — see above. Fix before continuing."
fi

# ----------------------------------------------------------------- systemd ----
say "Installing the systemd unit"
cp "$APP_DIR/deploy/cryptotrader.service" /etc/systemd/system/cryptotrader.service
systemctl daemon-reload
systemctl enable cryptotrader >/dev/null
echo "  unit installed and enabled (not started — run deploy-crypto.sh first)"

# ------------------------------------------------------------------ backups ----
say "Scheduling nightly database backups"
mkdir -p /var/backups/cryptotrader && chmod 700 /var/backups/cryptotrader
cat > /etc/cron.d/cryptotrader <<CRON
# Nightly crypto_trader backup at 01:30 (server local time). Keeps 14 days.
30 1 * * * root /bin/bash ${APP_DIR}/deploy/backup-crypto.sh >> /var/log/cryptotrader-backup.log 2>&1
CRON
chmod 644 /etc/cron.d/cryptotrader
echo "  cron installed (backups -> /var/backups/cryptotrader)"

# --------------------------------------------------------------------- TLS ----
say "TLS"
RESOLVED="$(getent ahostsv4 "$DOMAIN" 2>/dev/null | awk '{print $1; exit}')"
SERVER_IP="$(curl -s --max-time 8 https://api.ipify.org 2>/dev/null || true)"
if [[ -z "$RESOLVED" ]]; then
  warn "${DOMAIN} does not resolve yet. Create the A record -> ${SERVER_IP:-this server}, then run:"
  warn "    bash ${APP_DIR}/deploy/enable-tls-crypto.sh ${DOMAIN} ${CERTBOT_EMAIL:-you@example.com}"
elif [[ -n "$SERVER_IP" && "$RESOLVED" != "$SERVER_IP" ]]; then
  warn "${DOMAIN} resolves to ${RESOLVED}, but this server is ${SERVER_IP}. Fix the A record, then run enable-tls-crypto.sh."
else
  echo "  ${DOMAIN} resolves here — obtaining the certificate"
  bash "$APP_DIR/deploy/enable-tls-crypto.sh" "$DOMAIN" "$CERTBOT_EMAIL" || \
    warn "TLS did not complete — the HTTP bootstrap site is still serving. See enable-tls-crypto.sh output."
fi

cat <<DONE

$(printf '\033[1;32m')Provisioning complete.$(printf '\033[0m')

Next:
  1. Set the login secret in ${ENV_PATH} (TOTP_SECRET=).
  2. Deploy:   bash ${APP_DIR}/deploy/deploy-crypto.sh
  3. If TLS was skipped above, run enable-tls-crypto.sh once the A record is live.

DB password: ${DB_PASSWORD_FILE} (already in backend/.env).
DONE
