"""widen currency for crypto quote

Revision ID: 516dbd529d0d
Revises: 620db9176e5c
Create Date: 2026-08-13 21:39:47.367481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '516dbd529d0d'
down_revision: Union[str, Sequence[str], None] = '620db9176e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('securities', 'currency',
               existing_type=mysql.CHAR(length=3),
               type_=sa.String(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'ZAR'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('securities', 'currency',
               existing_type=sa.String(length=8),
               type_=mysql.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'ZAR'"))
    # ### end Alembic commands ###
