"""widen price precision for crypto

Revision ID: 620db9176e5c
Revises: 6672da5982d8
Create Date: 2026-08-13 21:32:46.077078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '620db9176e5c'
down_revision: Union[str, Sequence[str], None] = '6672da5982d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper_trades', 'entry_price',
               existing_type=mysql.DECIMAL(precision=15, scale=4),
               type_=sa.Numeric(precision=24, scale=10),
               existing_nullable=False)
    op.alter_column('paper_trades', 'stop_price',
               existing_type=mysql.DECIMAL(precision=15, scale=4),
               type_=sa.Numeric(precision=24, scale=10),
               existing_nullable=True)
    op.alter_column('paper_trades', 'exit_price',
               existing_type=mysql.DECIMAL(precision=15, scale=4),
               type_=sa.Numeric(precision=24, scale=10),
               existing_nullable=True)
    op.alter_column('paper_trades', 'pnl',
               existing_type=mysql.DECIMAL(precision=15, scale=4),
               type_=sa.Numeric(precision=24, scale=10),
               existing_nullable=True)
    op.alter_column('price_bars', 'open',
               existing_type=mysql.DECIMAL(precision=15, scale=4),
               type_=sa.Numeric(precision=24, scale=10),
               existing_nullable=False)
    op.alter_column('price_bars', 'high',
               existing_type=mysql.DECIMAL(precision=15, scale=4),
               type_=sa.Numeric(precision=24, scale=10),
               existing_nullable=False)
    op.alter_column('price_bars', 'low',
               existing_type=mysql.DECIMAL(precision=15, scale=4),
               type_=sa.Numeric(precision=24, scale=10),
               existing_nullable=False)
    op.alter_column('price_bars', 'close',
               existing_type=mysql.DECIMAL(precision=15, scale=4),
               type_=sa.Numeric(precision=24, scale=10),
               existing_nullable=False)
    op.alter_column('price_bars', 'adj_close',
               existing_type=mysql.DECIMAL(precision=15, scale=4),
               type_=sa.Numeric(precision=24, scale=10),
               existing_nullable=True)
    op.alter_column('signals', 'suggested_entry',
               existing_type=mysql.DECIMAL(precision=15, scale=4),
               type_=sa.Numeric(precision=24, scale=10),
               existing_nullable=True)
    op.alter_column('signals', 'suggested_stop',
               existing_type=mysql.DECIMAL(precision=15, scale=4),
               type_=sa.Numeric(precision=24, scale=10),
               existing_nullable=True)
    op.alter_column('trades', 'price',
               existing_type=mysql.DECIMAL(precision=15, scale=4),
               type_=sa.Numeric(precision=24, scale=10),
               existing_nullable=False)
    op.alter_column('trades', 'fees',
               existing_type=mysql.DECIMAL(precision=15, scale=4),
               type_=sa.Numeric(precision=24, scale=10),
               existing_nullable=False,
               existing_server_default=sa.text("'0.0000'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'fees',
               existing_type=sa.Numeric(precision=24, scale=10),
               type_=mysql.DECIMAL(precision=15, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text("'0.0000'"))
    op.alter_column('trades', 'price',
               existing_type=sa.Numeric(precision=24, scale=10),
               type_=mysql.DECIMAL(precision=15, scale=4),
               existing_nullable=False)
    op.alter_column('signals', 'suggested_stop',
               existing_type=sa.Numeric(precision=24, scale=10),
               type_=mysql.DECIMAL(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('signals', 'suggested_entry',
               existing_type=sa.Numeric(precision=24, scale=10),
               type_=mysql.DECIMAL(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('price_bars', 'adj_close',
               existing_type=sa.Numeric(precision=24, scale=10),
               type_=mysql.DECIMAL(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('price_bars', 'close',
               existing_type=sa.Numeric(precision=24, scale=10),
               type_=mysql.DECIMAL(precision=15, scale=4),
               existing_nullable=False)
    op.alter_column('price_bars', 'low',
               existing_type=sa.Numeric(precision=24, scale=10),
               type_=mysql.DECIMAL(precision=15, scale=4),
               existing_nullable=False)
    op.alter_column('price_bars', 'high',
               existing_type=sa.Numeric(precision=24, scale=10),
               type_=mysql.DECIMAL(precision=15, scale=4),
               existing_nullable=False)
    op.alter_column('price_bars', 'open',
               existing_type=sa.Numeric(precision=24, scale=10),
               type_=mysql.DECIMAL(precision=15, scale=4),
               existing_nullable=False)
    op.alter_column('paper_trades', 'pnl',
               existing_type=sa.Numeric(precision=24, scale=10),
               type_=mysql.DECIMAL(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('paper_trades', 'exit_price',
               existing_type=sa.Numeric(precision=24, scale=10),
               type_=mysql.DECIMAL(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('paper_trades', 'stop_price',
               existing_type=sa.Numeric(precision=24, scale=10),
               type_=mysql.DECIMAL(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('paper_trades', 'entry_price',
               existing_type=sa.Numeric(precision=24, scale=10),
               type_=mysql.DECIMAL(precision=15, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
