"""sens_announcements

Revision ID: 6672da5982d8
Revises: ac18b416ec12
Create Date: 2026-07-20 22:15:11.868939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6672da5982d8'
down_revision: Union[str, Sequence[str], None] = 'ac18b416ec12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sens_announcements',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('security_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=768), nullable=False),
    sa.Column('url_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('raw', mysql.JSON(), nullable=True),
    sa.Column('fetched_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    op.create_index('idx_sens_published', 'sens_announcements', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sens_published', table_name='sens_announcements')
    op.drop_table('sens_announcements')
    # ### end Alembic commands ###
