"""initial schema

Revision ID: e4ce7aee8ad4
Revises: 
Create Date: 2026-07-20 16:58:56.861815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4ce7aee8ad4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_series',
    sa.Column('series_code', sa.String(length=30), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('ingested_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('series_code', 'observation_date')
    )
    op.create_table('news_articles',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=768), nullable=False),
    sa.Column('url_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('raw', mysql.JSON(), nullable=True),
    sa.Column('fetched_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    op.create_index('idx_news_published', 'news_articles', ['published_at'], unique=False)
    op.create_table('provider_calls',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('called_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status_code', mysql.INTEGER(), nullable=True),
    sa.Column('rows_returned', mysql.INTEGER(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prov', 'provider_calls', ['provider', 'called_at'], unique=False)
    op.create_table('securities',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'ZAR'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('indicator_values',
    sa.Column('security_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('bar_datetime', sa.DateTime(), nullable=False),
    sa.Column('indicator', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('computed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('security_id', 'timeframe', 'bar_datetime', 'indicator')
    )
    op.create_table('news_sentiment',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('article_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('security_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('entity_symbol', sa.String(length=40), nullable=True),
    sa.Column('sentiment', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('relevance', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('model', sa.String(length=40), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sent_sec', 'news_sentiment', ['security_id', 'created_at'], unique=False)
    op.create_table('price_bars',
    sa.Column('security_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('bar_datetime', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('volume', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('is_delayed', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('ingested_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('security_id', 'timeframe', 'bar_datetime')
    )
    op.create_table('signals',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('security_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('horizon_days', mysql.SMALLINT(), server_default=sa.text('10'), nullable=False),
    sa.Column('direction', sa.Enum('BUY', 'SELL', 'HOLD', name='signaldirection'), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('technical_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('macro_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('suggested_entry', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('suggested_stop', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('suggested_size', mysql.INTEGER(), nullable=True),
    sa.Column('rationale', mysql.JSON(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACTED', 'EXPIRED', 'DISMISSED', name='signalstatus'), server_default=sa.text("'OPEN'"), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sig_gen', 'signals', ['generated_at'], unique=False)
    op.create_index('idx_sig_sec', 'signals', ['security_id', 'generated_at'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('security_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('added_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id')
    )
    op.create_table('paper_trades',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('signal_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('security_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('entry_datetime', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), nullable=False),
    sa.Column('stop_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('exit_datetime', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='papertradestatus'), server_default=sa.text("'OPEN'"), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('security_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='tradeside'), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('fees', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('trade_datetime', sa.DateTime(), nullable=False),
    sa.Column('linked_signal_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('rationale', sa.String(length=1000), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['linked_signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('paper_trades')
    op.drop_table('watchlist')
    op.drop_index('idx_sig_sec', table_name='signals')
    op.drop_index('idx_sig_gen', table_name='signals')
    op.drop_table('signals')
    op.drop_table('price_bars')
    op.drop_index('idx_sent_sec', table_name='news_sentiment')
    op.drop_table('news_sentiment')
    op.drop_table('indicator_values')
    op.drop_table('securities')
    op.drop_index('idx_prov', table_name='provider_calls')
    op.drop_table('provider_calls')
    op.drop_index('idx_news_published', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_table('macro_series')
    # ### end Alembic commands ###
